apiVersion: v1
kind: Pod
metadata:
  name: dropvault-tools-auth
  namespace: dropvault
spec:
  containers:
  - name: dropvault-auth
    image: docker.io/dropvault/auth-tool:v4
    env:
    - name: DATABASE_URL
      value: postgres://postgres:postgres@db-auth:5432/postgres?sslmode=disable
  restartPolicy: Never

