apiVersion: v1
kind: Pod
metadata:
  name: dropvault-tools-stock
  namespace: dropvault
spec:
  containers:
  - name: dropvault-stock
    image: docker.io/dropvault/dropvault-storage-tools:v1
    env:
    - name: DATABASE_URL
      value: postgres://postgres:postgres@db-stock/postgres?sslmode=disable
  restartPolicy: Never
